-- CC ANALYTICS · CICLO DE VIDA DE VENTAS
-- Conserva cancelaciones y devoluciones por mes, y convierte ventas anunciadas
-- en ventas posteadas reales sin duplicar registros.

alter table public.analytics_sales
  add column if not exists sale_status text not null default 'posteada',
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by uuid,
  add column if not exists cancellation_category text,
  add column if not exists cancellation_reason text;

do $$
begin
  alter table public.analytics_sales
    add constraint analytics_sales_status_check
    check (sale_status in ('posteada', 'cancelada', 'devuelta'));
exception
  when duplicate_object then null;
end $$;

create table if not exists public.analytics_sale_cancellations (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.analytics_sales(id) on delete restrict,
  seller_id uuid,
  seller_name text not null,
  seller_code text,
  supervisor_profile_id uuid not null,
  department text not null,
  zone text not null,
  original_sale_date date not null,
  cancellation_date date not null default current_date,
  cancellation_month date not null,
  category text not null,
  reason text not null,
  sale_units integer not null,
  amount_billed numeric,
  city text,
  service text,
  contract_service text,
  source_type text,
  sale_snapshot jsonb not null default '{}'::jsonb,
  created_by uuid not null,
  created_at timestamptz not null default now(),
  unique (sale_id)
);

do $$
begin
  alter table public.analytics_sale_cancellations
    add constraint analytics_sale_cancellations_category_check
    check (category in (
      'devolucion',
      'cliente_desistio',
      'duplicada',
      'error_registro',
      'sin_cobertura',
      'pago_rechazado',
      'fraude',
      'otra'
    ));
exception
  when duplicate_object then null;
end $$;

create index if not exists analytics_sale_cancellations_month_idx
  on public.analytics_sale_cancellations(cancellation_month, supervisor_profile_id);
create index if not exists analytics_sale_cancellations_category_idx
  on public.analytics_sale_cancellations(category, cancellation_date);

alter table public.analytics_sale_cancellations enable row level security;

drop policy if exists "analytics sale cancellations scoped select"
  on public.analytics_sale_cancellations;
create policy "analytics sale cancellations scoped select"
  on public.analytics_sale_cancellations
  for select
  to authenticated
  using (public.current_user_can_manage_supervisor(supervisor_profile_id));

grant select on public.analytics_sale_cancellations to authenticated;

-- Las ventas canceladas permanecen en la base para auditoría, pero dejan de ser
-- visibles para dashboards, rankings, reportes y cargas ordinarias.
drop policy if exists "analytics sales hierarchical select" on public.analytics_sales;
create policy "analytics sales hierarchical select"
  on public.analytics_sales
  for select
  to authenticated
  using (
    sale_status = 'posteada'
    and public.current_user_can_view_sale(
      department,
      zone,
      supervisor_profile_id,
      created_by
    )
  );

-- En las consultas ordinarias solo aparecen anunciadas pendientes. Las
-- posteadas y eliminadas siguen archivadas para auditoría.
drop policy if exists "analytics announced sales scoped select"
  on public.analytics_announced_sales;
create policy "analytics announced sales scoped select"
  on public.analytics_announced_sales
  for select
  to authenticated
  using (
    status = 'anunciada'
    and public.current_user_can_view_sale(
      department,
      zone,
      supervisor_profile_id,
      created_by
    )
  );

create or replace function public.analytics_cancel_posted_sale(
  target_id bigint,
  target_category text,
  target_reason text,
  target_cancellation_date date default current_date
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  sale_row public.analytics_sales%rowtype;
  cancellation_id bigint;
  clean_category text := lower(trim(coalesce(target_category, '')));
  clean_reason text := trim(coalesce(target_reason, ''));
begin
  if clean_category not in (
    'devolucion',
    'cliente_desistio',
    'duplicada',
    'error_registro',
    'sin_cobertura',
    'pago_rechazado',
    'fraude',
    'otra'
  ) then
    raise exception 'Selecciona un motivo de cancelación válido';
  end if;

  if length(clean_reason) < 5 then
    raise exception 'Escribe una explicación de al menos 5 caracteres';
  end if;

  if target_cancellation_date is null then
    raise exception 'La fecha de cancelación es obligatoria';
  end if;

  select * into sale_row
  from public.analytics_sales
  where id = target_id
  for update;

  if sale_row.id is null then
    raise exception 'Venta posteada no encontrada';
  end if;

  if sale_row.sale_status <> 'posteada' then
    raise exception 'La venta ya fue cancelada o devuelta';
  end if;

  if sale_row.supervisor_profile_id is null
     or not public.current_user_can_manage_supervisor(sale_row.supervisor_profile_id) then
    raise exception 'No tienes permiso para cancelar esta venta';
  end if;

  insert into public.analytics_sale_cancellations (
    sale_id,
    seller_id,
    seller_name,
    seller_code,
    supervisor_profile_id,
    department,
    zone,
    original_sale_date,
    cancellation_date,
    cancellation_month,
    category,
    reason,
    sale_units,
    amount_billed,
    city,
    service,
    contract_service,
    source_type,
    sale_snapshot,
    created_by
  ) values (
    sale_row.id,
    sale_row.seller_id,
    sale_row.seller_name,
    sale_row.seller_code,
    sale_row.supervisor_profile_id,
    sale_row.department,
    sale_row.zone,
    sale_row.sale_date,
    target_cancellation_date,
    date_trunc('month', target_cancellation_date)::date,
    clean_category,
    clean_reason,
    greatest(coalesce(sale_row.sale_units, 1), 1),
    sale_row.amount_billed,
    sale_row.city,
    sale_row.service,
    sale_row.contract_service,
    sale_row.source_type,
    to_jsonb(sale_row),
    auth.uid()
  )
  returning id into cancellation_id;

  update public.analytics_sales
  set sale_status = case
        when clean_category = 'devolucion' then 'devuelta'
        else 'cancelada'
      end,
      cancelled_at = target_cancellation_date::timestamptz + interval '12 hours',
      cancelled_by = auth.uid(),
      cancellation_category = clean_category,
      cancellation_reason = clean_reason,
      manual_override = true,
      corrected_by = auth.uid(),
      correction_reason = clean_reason,
      updated_at = now()
  where id = target_id;

  insert into public.analytics_audit_log (
    actor_id,
    action,
    entity_type,
    entity_id,
    department,
    zone,
    metadata
  ) values (
    auth.uid(),
    case when clean_category = 'devolucion'
      then 'posted_sale_returned'
      else 'posted_sale_cancelled'
    end,
    'analytics_sale',
    target_id::text,
    sale_row.department,
    sale_row.zone,
    jsonb_build_object(
      'cancellation_id', cancellation_id,
      'category', clean_category,
      'reason', clean_reason,
      'cancellation_date', target_cancellation_date,
      'sale_units', greatest(coalesce(sale_row.sale_units, 1), 1),
      'amount_billed', sale_row.amount_billed,
      'before', to_jsonb(sale_row)
    )
  );

  return cancellation_id;
end;
$$;

create or replace function public.analytics_post_announced_sale(
  target_id bigint,
  target_post_date date,
  target_reason text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  announced_row public.analytics_announced_sales%rowtype;
  seller_row public.analytics_sellers%rowtype;
  supervisor_name text;
  new_sale_id bigint;
  clean_reason text := trim(coalesce(target_reason, ''));
begin
  if target_post_date is null then
    raise exception 'La fecha de posteo es obligatoria';
  end if;

  if length(clean_reason) < 5 then
    raise exception 'Escribe una confirmación de al menos 5 caracteres';
  end if;

  select * into announced_row
  from public.analytics_announced_sales
  where id = target_id
  for update;

  if announced_row.id is null then
    raise exception 'Venta anunciada no encontrada';
  end if;

  if announced_row.status <> 'anunciada' then
    raise exception 'La venta anunciada ya fue procesada';
  end if;

  if not public.current_user_can_manage_supervisor(announced_row.supervisor_profile_id) then
    raise exception 'No tienes permiso para postear esta venta anunciada';
  end if;

  select * into seller_row
  from public.analytics_sellers
  where id = announced_row.seller_id;

  if seller_row.id is null then
    raise exception 'La venta anunciada debe estar vinculada a un vendedor oficial';
  end if;

  select full_name into supervisor_name
  from public.analytics_profiles
  where id = announced_row.supervisor_profile_id;

  insert into public.analytics_sales (
    source_import_id,
    department,
    zone,
    seller_profile_id,
    supervisor_profile_id,
    seller_code,
    seller_name,
    team,
    sale_date,
    city,
    sale_type,
    service,
    medium,
    is_primary,
    contract_service,
    amount_billed,
    payload,
    created_by,
    seller_id,
    source_type,
    import_confidence,
    detected_fields,
    sale_units,
    snapshot_as_of,
    manual_override,
    corrected_by,
    correction_reason,
    sale_status
  ) values (
    announced_row.source_import_id,
    announced_row.department,
    announced_row.zone,
    null,
    announced_row.supervisor_profile_id,
    seller_row.seller_code,
    seller_row.full_name,
    coalesce(supervisor_name, 'Equipo'),
    target_post_date,
    announced_row.city,
    'Venta anunciada convertida',
    announced_row.service,
    'Conversión de anunciada',
    true,
    announced_row.contract_service,
    announced_row.amount_announced,
    coalesce(announced_row.payload, '{}'::jsonb)
      || jsonb_build_object('announced_sale_id', announced_row.id),
    auth.uid(),
    seller_row.id,
    'announced',
    coalesce(announced_row.import_confidence, 1),
    coalesce(announced_row.detected_fields, '{}'::jsonb)
      || jsonb_build_object('converted_from_announced', true),
    greatest(coalesce(announced_row.sale_units, 1), 1),
    target_post_date,
    true,
    auth.uid(),
    clean_reason,
    'posteada'
  )
  returning id into new_sale_id;

  update public.analytics_announced_sales
  set status = 'posteada',
      linked_sale_id = new_sale_id,
      expected_post_date = target_post_date,
      manual_override = true,
      corrected_by = auth.uid(),
      correction_reason = clean_reason,
      updated_at = now()
  where id = target_id;

  insert into public.analytics_audit_log (
    actor_id,
    action,
    entity_type,
    entity_id,
    department,
    zone,
    metadata
  ) values (
    auth.uid(),
    'announced_sale_posted',
    'analytics_announced_sale',
    target_id::text,
    announced_row.department,
    announced_row.zone,
    jsonb_build_object(
      'linked_sale_id', new_sale_id,
      'post_date', target_post_date,
      'reason', clean_reason,
      'before', to_jsonb(announced_row)
    )
  );

  return new_sale_id;
end;
$$;

create or replace function public.analytics_delete_announced_sale(
  target_id bigint,
  target_reason text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  announced_row public.analytics_announced_sales%rowtype;
  clean_reason text := trim(coalesce(target_reason, ''));
begin
  if length(clean_reason) < 5 then
    raise exception 'Escribe un motivo de al menos 5 caracteres';
  end if;

  select * into announced_row
  from public.analytics_announced_sales
  where id = target_id
  for update;

  if announced_row.id is null then
    raise exception 'Venta anunciada no encontrada';
  end if;

  if announced_row.status <> 'anunciada' then
    raise exception 'La venta anunciada ya fue procesada';
  end if;

  if not public.current_user_can_manage_supervisor(announced_row.supervisor_profile_id) then
    raise exception 'No tienes permiso para eliminar esta venta anunciada';
  end if;

  update public.analytics_announced_sales
  set status = 'cancelada',
      manual_override = true,
      corrected_by = auth.uid(),
      correction_reason = clean_reason,
      updated_at = now()
  where id = target_id;

  insert into public.analytics_audit_log (
    actor_id,
    action,
    entity_type,
    entity_id,
    department,
    zone,
    metadata
  ) values (
    auth.uid(),
    'announced_sale_deleted',
    'analytics_announced_sale',
    target_id::text,
    announced_row.department,
    announced_row.zone,
    jsonb_build_object(
      'reason', clean_reason,
      'before', to_jsonb(announced_row)
    )
  );

  return target_id;
end;
$$;

-- Compatibilidad con los botones existentes de Ingreso de ventas: un cambio
-- directo de estado también ejecuta la conversión real o el archivado.
create or replace function public.analytics_announced_status_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  seller_row public.analytics_sellers%rowtype;
  supervisor_name text;
  generated_sale_id bigint;
  actor uuid := auth.uid();
begin
  if new.status = old.status then
    return new;
  end if;

  if old.status <> 'anunciada' then
    raise exception 'Una venta anunciada procesada no puede cambiar nuevamente de estado';
  end if;

  if not public.current_user_can_manage_supervisor(old.supervisor_profile_id)
     and old.created_by <> actor then
    raise exception 'No tienes permiso para procesar esta venta anunciada';
  end if;

  if new.status = 'posteada' and new.linked_sale_id is null then
    select * into seller_row
    from public.analytics_sellers
    where id = old.seller_id;

    if seller_row.id is null then
      raise exception 'La venta anunciada debe estar vinculada a un vendedor oficial';
    end if;

    select full_name into supervisor_name
    from public.analytics_profiles
    where id = old.supervisor_profile_id;

    insert into public.analytics_sales (
      source_import_id,
      department,
      zone,
      seller_profile_id,
      supervisor_profile_id,
      seller_code,
      seller_name,
      team,
      sale_date,
      city,
      sale_type,
      service,
      medium,
      is_primary,
      contract_service,
      amount_billed,
      payload,
      created_by,
      seller_id,
      source_type,
      import_confidence,
      detected_fields,
      sale_units,
      snapshot_as_of,
      manual_override,
      corrected_by,
      correction_reason,
      sale_status
    ) values (
      old.source_import_id,
      old.department,
      old.zone,
      null,
      old.supervisor_profile_id,
      seller_row.seller_code,
      seller_row.full_name,
      coalesce(supervisor_name, 'Equipo'),
      current_date,
      old.city,
      'Venta anunciada convertida',
      old.service,
      'Conversión de anunciada',
      true,
      old.contract_service,
      old.amount_announced,
      coalesce(old.payload, '{}'::jsonb)
        || jsonb_build_object('announced_sale_id', old.id),
      coalesce(actor, old.created_by),
      seller_row.id,
      'announced',
      coalesce(old.import_confidence, 1),
      coalesce(old.detected_fields, '{}'::jsonb)
        || jsonb_build_object('converted_from_announced', true),
      greatest(coalesce(old.sale_units, 1), 1),
      current_date,
      true,
      actor,
      coalesce(nullif(trim(new.correction_reason), ''), 'Posteada desde Ingreso de ventas'),
      'posteada'
    ) returning id into generated_sale_id;

    new.linked_sale_id := generated_sale_id;
    new.manual_override := true;
    new.corrected_by := actor;
    new.correction_reason := coalesce(
      nullif(trim(new.correction_reason), ''),
      'Posteada desde Ingreso de ventas'
    );
  elsif new.status = 'cancelada' then
    new.manual_override := true;
    new.corrected_by := actor;
    new.correction_reason := coalesce(
      nullif(trim(new.correction_reason), ''),
      'Eliminada desde Ingreso de ventas'
    );
  elsif new.status not in ('posteada', 'cancelada') then
    raise exception 'Transición de estado no válida';
  end if;

  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists analytics_announced_status_transition_trigger
  on public.analytics_announced_sales;
create trigger analytics_announced_status_transition_trigger
before update of status on public.analytics_announced_sales
for each row
execute function public.analytics_announced_status_transition();

grant execute on function public.analytics_cancel_posted_sale(bigint, text, text, date)
  to authenticated;
grant execute on function public.analytics_post_announced_sale(bigint, date, text)
  to authenticated;
grant execute on function public.analytics_delete_announced_sale(bigint, text)
  to authenticated;
